[tox]
envlist =
  py{311,312,313,314}
  cov{_erase,313,314}

[gh-actions]
python =
  3.11: py311
  3.12: py312
  3.13: py313
  3.14: py314

[pytest]
testpaths = testit
python_files = testaa_*.py
pythonpath = .

[testenv]
usedevelop = true
deps = pytest
commands = py.test {posargs:testit}

[testenv:cov_erase]
basepython = 3.14
deps =
  coverage
commands = coverage erase

[testenv:cov313]
basepython = 3.13
deps =
  pytest-cov
commands = py.test --cov=katso --cov-report=xml --cov-append {posargs:testit}

[testenv:cov314]
basepython = 3.14
deps =
  pytest-cov
commands = py.test --cov=katso --cov-report=xml --cov-append {posargs:testit}
